#!/bin/sh

echo "generate/update version.h ..."

VERSION_FILE=version.h

MAJOR_VERSION="1.0"
MINOR_VERSION=`git log | grep -e 'commit [a-zA-Z0-9]*' | wc -l`

echo "//This file is generated by gen_version_c.sh don't edit it!" > $VERSION_FILE
date +'#define BUILD_TIME "%Y-%m-%d %H:%M:%S"' >> $VERSION_FILE
gitVersion=`git rev-parse --short HEAD`

if git status -s | grep -q "\<M"; then
	MODIFY="*"
fi

echo "#define GIT_COMMIT \"$gitVersion$MODIFY\"" >> $VERSION_FILE
echo "#define EXEC_VERSION \"$MAJOR_VERSION.$MINOR_VERSION\"" >> $VERSION_FILE

